/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as CustomKitRouteImport } from './routes/custom-kit'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopHandleRouteImport } from './routes/shop.$handle'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as HelpSizeGuideRouteImport } from './routes/help.size-guide'
import { Route as HelpShippingReturnsRouteImport } from './routes/help.shipping-returns'
import { Route as HelpFaqRouteImport } from './routes/help.faq'
import { Route as HelpFabricCareRouteImport } from './routes/help.fabric-care'
import { Route as AdminKitRequestsRouteImport } from './routes/admin.kit-requests'
import { Route as CustomKitStatusRequestIdRouteImport } from './routes/custom-kit.status.$requestId'
import { Route as AdminKitRequestsIdRouteImport } from './routes/admin.kit-requests.$id'

const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomKitRoute = CustomKitRouteImport.update({
  id: '/custom-kit',
  path: '/custom-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopHandleRoute = ShopHandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => ShopRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const HelpSizeGuideRoute = HelpSizeGuideRouteImport.update({
  id: '/help/size-guide',
  path: '/help/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpShippingReturnsRoute = HelpShippingReturnsRouteImport.update({
  id: '/help/shipping-returns',
  path: '/help/shipping-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpFaqRoute = HelpFaqRouteImport.update({
  id: '/help/faq',
  path: '/help/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpFabricCareRoute = HelpFabricCareRouteImport.update({
  id: '/help/fabric-care',
  path: '/help/fabric-care',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKitRequestsRoute = AdminKitRequestsRouteImport.update({
  id: '/admin/kit-requests',
  path: '/admin/kit-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomKitStatusRequestIdRoute =
  CustomKitStatusRequestIdRouteImport.update({
    id: '/status/$requestId',
    path: '/status/$requestId',
    getParentRoute: () => CustomKitRoute,
  } as any)
const AdminKitRequestsIdRoute = AdminKitRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminKitRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-kit': typeof CustomKitRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/admin/kit-requests': typeof AdminKitRequestsRouteWithChildren
  '/help/fabric-care': typeof HelpFabricCareRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/shipping-returns': typeof HelpShippingReturnsRoute
  '/help/size-guide': typeof HelpSizeGuideRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/admin/kit-requests/$id': typeof AdminKitRequestsIdRoute
  '/custom-kit/status/$requestId': typeof CustomKitStatusRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-kit': typeof CustomKitRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/admin/kit-requests': typeof AdminKitRequestsRouteWithChildren
  '/help/fabric-care': typeof HelpFabricCareRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/shipping-returns': typeof HelpShippingReturnsRoute
  '/help/size-guide': typeof HelpSizeGuideRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/admin/kit-requests/$id': typeof AdminKitRequestsIdRoute
  '/custom-kit/status/$requestId': typeof CustomKitStatusRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/custom-kit': typeof CustomKitRouteWithChildren
  '/journal': typeof JournalRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sustainability': typeof SustainabilityRoute
  '/admin/kit-requests': typeof AdminKitRequestsRouteWithChildren
  '/help/fabric-care': typeof HelpFabricCareRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/shipping-returns': typeof HelpShippingReturnsRoute
  '/help/size-guide': typeof HelpSizeGuideRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/shop/$handle': typeof ShopHandleRoute
  '/admin/kit-requests/$id': typeof AdminKitRequestsIdRoute
  '/custom-kit/status/$requestId': typeof CustomKitStatusRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-kit'
    | '/journal'
    | '/shop'
    | '/sustainability'
    | '/admin/kit-requests'
    | '/help/fabric-care'
    | '/help/faq'
    | '/help/shipping-returns'
    | '/help/size-guide'
    | '/journal/$slug'
    | '/shop/$handle'
    | '/admin/kit-requests/$id'
    | '/custom-kit/status/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/custom-kit'
    | '/journal'
    | '/shop'
    | '/sustainability'
    | '/admin/kit-requests'
    | '/help/fabric-care'
    | '/help/faq'
    | '/help/shipping-returns'
    | '/help/size-guide'
    | '/journal/$slug'
    | '/shop/$handle'
    | '/admin/kit-requests/$id'
    | '/custom-kit/status/$requestId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/custom-kit'
    | '/journal'
    | '/shop'
    | '/sustainability'
    | '/admin/kit-requests'
    | '/help/fabric-care'
    | '/help/faq'
    | '/help/shipping-returns'
    | '/help/size-guide'
    | '/journal/$slug'
    | '/shop/$handle'
    | '/admin/kit-requests/$id'
    | '/custom-kit/status/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CustomKitRoute: typeof CustomKitRouteWithChildren
  JournalRoute: typeof JournalRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  SustainabilityRoute: typeof SustainabilityRoute
  AdminKitRequestsRoute: typeof AdminKitRequestsRouteWithChildren
  HelpFabricCareRoute: typeof HelpFabricCareRoute
  HelpFaqRoute: typeof HelpFaqRoute
  HelpShippingReturnsRoute: typeof HelpShippingReturnsRoute
  HelpSizeGuideRoute: typeof HelpSizeGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-kit': {
      id: '/custom-kit'
      path: '/custom-kit'
      fullPath: '/custom-kit'
      preLoaderRoute: typeof CustomKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$handle': {
      id: '/shop/$handle'
      path: '/$handle'
      fullPath: '/shop/$handle'
      preLoaderRoute: typeof ShopHandleRouteImport
      parentRoute: typeof ShopRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/help/size-guide': {
      id: '/help/size-guide'
      path: '/help/size-guide'
      fullPath: '/help/size-guide'
      preLoaderRoute: typeof HelpSizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/shipping-returns': {
      id: '/help/shipping-returns'
      path: '/help/shipping-returns'
      fullPath: '/help/shipping-returns'
      preLoaderRoute: typeof HelpShippingReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/faq': {
      id: '/help/faq'
      path: '/help/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof HelpFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/fabric-care': {
      id: '/help/fabric-care'
      path: '/help/fabric-care'
      fullPath: '/help/fabric-care'
      preLoaderRoute: typeof HelpFabricCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kit-requests': {
      id: '/admin/kit-requests'
      path: '/admin/kit-requests'
      fullPath: '/admin/kit-requests'
      preLoaderRoute: typeof AdminKitRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-kit/status/$requestId': {
      id: '/custom-kit/status/$requestId'
      path: '/status/$requestId'
      fullPath: '/custom-kit/status/$requestId'
      preLoaderRoute: typeof CustomKitStatusRequestIdRouteImport
      parentRoute: typeof CustomKitRoute
    }
    '/admin/kit-requests/$id': {
      id: '/admin/kit-requests/$id'
      path: '/$id'
      fullPath: '/admin/kit-requests/$id'
      preLoaderRoute: typeof AdminKitRequestsIdRouteImport
      parentRoute: typeof AdminKitRequestsRoute
    }
  }
}

interface CustomKitRouteChildren {
  CustomKitStatusRequestIdRoute: typeof CustomKitStatusRequestIdRoute
}

const CustomKitRouteChildren: CustomKitRouteChildren = {
  CustomKitStatusRequestIdRoute: CustomKitStatusRequestIdRoute,
}

const CustomKitRouteWithChildren = CustomKitRoute._addFileChildren(
  CustomKitRouteChildren,
)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface ShopRouteChildren {
  ShopHandleRoute: typeof ShopHandleRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopHandleRoute: ShopHandleRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

interface AdminKitRequestsRouteChildren {
  AdminKitRequestsIdRoute: typeof AdminKitRequestsIdRoute
}

const AdminKitRequestsRouteChildren: AdminKitRequestsRouteChildren = {
  AdminKitRequestsIdRoute: AdminKitRequestsIdRoute,
}

const AdminKitRequestsRouteWithChildren =
  AdminKitRequestsRoute._addFileChildren(AdminKitRequestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CustomKitRoute: CustomKitRouteWithChildren,
  JournalRoute: JournalRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SustainabilityRoute: SustainabilityRoute,
  AdminKitRequestsRoute: AdminKitRequestsRouteWithChildren,
  HelpFabricCareRoute: HelpFabricCareRoute,
  HelpFaqRoute: HelpFaqRoute,
  HelpShippingReturnsRoute: HelpShippingReturnsRoute,
  HelpSizeGuideRoute: HelpSizeGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
